[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.partitions = ../../partitions.csv
build_flags = -I../../include
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
