#pragma once
// Generated by tools/export_dense_int8_header.py. Do not edit by hand.
// Stored float approximation: int8_value * the matching scale below.
// Input normalization: (sensor_value - kInputMean) / kInputScale.
#include <Arduino.h>

namespace thermal_risk_model {
constexpr size_t kInputSize = 20;
constexpr size_t kHiddenSize = 12;
constexpr size_t kOutputSize = 3;
constexpr float kInputMean[kInputSize] = {29.4871578f, 71.2216187f, 29.5621281f, 71.2025604f, 29.6491947f, 71.1796722f, 29.7483711f, 71.1536026f, 29.8597145f, 71.123848f, 29.9956341f, 71.0884094f, 30.1708317f, 71.0413742f, 30.3858395f, 70.9834747f, 30.6404819f, 70.9143982f, 30.9346657f, 70.8348007f};
constexpr float kInputScale[kInputSize] = {3.03807831f, 14.7815733f, 3.05086732f, 14.7823811f, 3.11202717f, 14.7836094f, 3.22647882f, 14.7858572f, 3.40408731f, 14.7897673f, 3.66566968f, 14.7963657f, 4.05017138f, 14.8065901f, 4.59711599f, 14.8223257f, 5.33947277f, 14.8459444f, 6.29969358f, 14.8823938f};
constexpr float kDense1WeightScale = 0.0404582657f;
constexpr float kDense1BiasScale = 0.0562077761f;
constexpr float kDense2WeightScale = 0.0701608807f;
constexpr float kDense2BiasScale = 0.051895719f;
constexpr int8_t kDense1Weights[kInputSize][kHiddenSize] = {{-51, -1, 0, -28, 3, 2, 16, -17, 10, 13, -14, -51}, {-13, 23, -1, -36, 15, 9, 1, -13, -12, 1, 8, 36}, {-38, 33, 14, -18, -3, 7, 21, -30, 1, -3, -4, -17}, {1, 15, 3, -35, 3, 1, 12, -11, -11, -4, 6, 33}, {-2, 18, 13, -16, -7, -3, 1, -38, 17, -2, -9, 0}, {21, 5, -8, -40, 4, 6, 5, -8, 9, -2, -3, 24}, {-6, 6, -4, -11, -8, 1, -5, -57, 11, -11, -2, -17}, {2, 18, 9, -10, -19, 5, -11, -9, 0, 8, -5, 18}, {10, 11, -2, -19, 16, -4, 9, -43, -6, -2, -11, 21}, {-3, 25, -2, -35, 10, 0, -1, -16, -5, -4, -2, 19}, {24, 8, -23, -7, 1, -5, -10, -31, -25, 15, -7, 8}, {-15, 20, 1, -23, -3, -11, 6, -12, 3, 13, -17, 5}, {8, -7, -22, -11, -8, 4, -12, -15, -23, 3, -4, -7}, {5, 34, -2, -47, -4, 5, -2, -5, -4, 1, 9, -19}, {3, 20, -24, -13, -1, -7, -28, -7, -40, 18, 16, -7}, {-8, 29, 4, -31, 7, -4, 19, -7, -12, -2, -12, 16}, {-16, 15, -57, -15, -3, 7, -37, -8, -47, 18, 24, -15}, {16, 49, -11, -29, -3, -11, 20, 3, -5, -25, 6, -5}, {-14, 17, -85, -80, -33, -7, -58, -44, -52, 127, 57, -34}, {18, 42, -3, -28, 5, 8, 26, -7, 3, 5, -14, -10}};
constexpr int8_t kDense1Bias[kHiddenSize] = {104, -26, 92, 85, 121, -11, 64, 34, 62, -81, -127, 79};
constexpr int8_t kDense2Weights[kHiddenSize][kOutputSize] = {{14, 28, -12}, {-19, -4, 15}, {9, -4, -26}, {7, 7, -16}, {42, 19, -70}, {-12, -2, -2}, {36, -13, -28}, {-16, 11, -6}, {26, -22, 2}, {-127, -4, 7}, {-2, -53, 51}, {-18, 9, -39}};
constexpr int8_t kDense2Bias[kOutputSize] = {37, 120, -127};
}  // namespace thermal_risk_model
