#!/usr/bin/env python3
"""Convert the teaching dense-network JSON into an ESP32 C++ INT8-weight header."""

import json
from pathlib import Path

import numpy as np


SOURCE = Path("artifacts/heatgun_dense_nn.json")
OUTPUT = Path("include/thermal_risk_model.h")


def quantize(values):
    values = np.asarray(values, dtype=np.float32)
    scale = float(np.max(np.abs(values)) / 127.0) or 1.0
    return np.clip(np.rint(values / scale), -127, 127).astype(np.int8), scale


def cpp_array(values):
    if values.ndim == 1:
        return "{" + ", ".join(str(int(value)) for value in values) + "}"
    return "{" + ", ".join(cpp_array(row) for row in values) + "}"


def main():
    model = json.loads(SOURCE.read_text())
    w1, w1_scale = quantize(model["dense_1_weights"])
    b1, b1_scale = quantize(model["dense_1_bias"])
    w2, w2_scale = quantize(model["dense_2_weights"])
    b2, b2_scale = quantize(model["dense_2_bias"])
    mean = ", ".join(f"{value:.9g}f" for value in model["scaler_mean"])
    scale = ", ".join(f"{value:.9g}f" for value in model["scaler_scale"])
    text = f'''#pragma once
// Generated by tools/export_dense_int8_header.py. Do not edit by hand.
#include <Arduino.h>

namespace thermal_risk_model {{
constexpr size_t kInputSize = 20;
constexpr size_t kHiddenSize = 12;
constexpr size_t kOutputSize = 3;
constexpr float kInputMean[kInputSize] = {{{mean}}};
constexpr float kInputScale[kInputSize] = {{{scale}}};
constexpr float kDense1WeightScale = {w1_scale:.9g}f;
constexpr float kDense1BiasScale = {b1_scale:.9g}f;
constexpr float kDense2WeightScale = {w2_scale:.9g}f;
constexpr float kDense2BiasScale = {b2_scale:.9g}f;
constexpr int8_t kDense1Weights[kInputSize][kHiddenSize] = {cpp_array(w1)};
constexpr int8_t kDense1Bias[kHiddenSize] = {cpp_array(b1)};
constexpr int8_t kDense2Weights[kHiddenSize][kOutputSize] = {cpp_array(w2)};
constexpr int8_t kDense2Bias[kOutputSize] = {cpp_array(b2)};
}}  // namespace thermal_risk_model
'''
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
