#!/usr/bin/env python3
"""Convert the teaching dense-network JSON into an ESP32 C++ header.

The trained model is saved as readable floating-point JSON. ESP32 flash is
limited, so this script stores each weight or bias as an INT8 value from -127
to 127 plus one scale value for its complete array.

The firmware reconstructs an approximation with:

    float_value = int8_value * array_scale

This is weight storage quantization for a small teaching model. The current
firmware dequantizes during inference; it is not a fully integer TFLite model.
"""

import json
from pathlib import Path

import numpy as np


SOURCE = Path("artifacts/heatgun_dense_nn.json")
OUTPUT = Path("include/thermal_risk_model.h")


def quantize(values):
    """Symmetrically quantize one weight/bias array and return its scale.

    The largest absolute value maps to approximately -127 or 127. Keeping zero
    exactly at zero makes the conversion simple to explain and implement.
    """
    values = np.asarray(values, dtype=np.float32)

    # One shared scale preserves the relative size of every value in this
    # array. The fallback handles an all-zero array without dividing by zero.
    scale = float(np.max(np.abs(values)) / 127.0) or 1.0

    # Divide by the scale, round to the nearest integer, and clip to the chosen
    # symmetric INT8 range. -128 is deliberately unused for symmetry.
    return np.clip(np.rint(values / scale), -127, 127).astype(np.int8), scale


def cpp_array(values):
    """Recursively format a NumPy vector or matrix as a C++ initializer."""
    if values.ndim == 1:
        return "{" + ", ".join(str(int(value)) for value in values) + "}"
    return "{" + ", ".join(cpp_array(row) for row in values) + "}"


def main():
    # Load the floating-point scaler, weights, biases, and model metadata saved
    # by train_heatgun_neural_net.py.
    model = json.loads(SOURCE.read_text())

    # Quantize each parameter array independently. Separate scales work here
    # because firmware converts every stored value back to float before use.
    w1, w1_scale = quantize(model["dense_1_weights"])
    b1, b1_scale = quantize(model["dense_1_bias"])
    w2, w2_scale = quantize(model["dense_2_weights"])
    b2, b2_scale = quantize(model["dense_2_bias"])
    # Input mean/scale remain float because normalization happens before the
    # dense layers and these arrays are tiny (20 values each).
    mean = ", ".join(f"{value:.9g}f" for value in model["scaler_mean"])
    scale = ", ".join(f"{value:.9g}f" for value in model["scaler_scale"])
    # Generate a header that can be included directly by Arduino/PlatformIO.
    # constexpr keeps these fixed model values read-only.
    text = f'''#pragma once
// Generated by tools/export_dense_int8_header.py. Do not edit by hand.
// Stored float approximation: int8_value * the matching scale below.
// Input normalization: (sensor_value - kInputMean) / kInputScale.
#include <Arduino.h>

namespace thermal_risk_model {{
constexpr size_t kInputSize = 20;
constexpr size_t kHiddenSize = 12;
constexpr size_t kOutputSize = 3;
constexpr float kInputMean[kInputSize] = {{{mean}}};
constexpr float kInputScale[kInputSize] = {{{scale}}};
constexpr float kDense1WeightScale = {w1_scale:.9g}f;
constexpr float kDense1BiasScale = {b1_scale:.9g}f;
constexpr float kDense2WeightScale = {w2_scale:.9g}f;
constexpr float kDense2BiasScale = {b2_scale:.9g}f;
constexpr int8_t kDense1Weights[kInputSize][kHiddenSize] = {cpp_array(w1)};
constexpr int8_t kDense1Bias[kHiddenSize] = {cpp_array(b1)};
constexpr int8_t kDense2Weights[kHiddenSize][kOutputSize] = {cpp_array(w2)};
constexpr int8_t kDense2Bias[kOutputSize] = {cpp_array(b2)};
}}  // namespace thermal_risk_model
'''
    # Create include/ on a fresh clone, then replace the previous generated
    # header with this model version.
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
